### ISSUE TITLE
sbt import 

### ISSUE THREAD

**Issue by xpavlic4** [ignasi35/lagom-pet-store#1]
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.lightbend.lagom#lagom-descriptor-generator-sbt-plugin;0.0.2: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.lightbend.lagom:lagom-descriptor-generator-sbt-plugin:0.0.2 (scalaVersion=2.10, sbtVersion=0.13)
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.lightbend.lagom:lagom-descriptor-generator-sbt-plugin:0.0.2 (scalaVersion=2.10, sbtVersion=0.13) (G:\git\lagom-pet-store\project\plugins.sbt#L8-9)
[warn] 		  +- default:lagom-pet-store-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
sbt.ResolveException: unresolved dependency: com.lightbend.lagom#lagom-descriptor-generator-sbt-plugin;0.0.2: not found

**Comment by ignasi35** [comment]
Hi @xpavlic4, we noticed the issue few hours ago and it should be fixed by now (maybe the current setup needs more time propagating on bintray's network).

**Comment by markusjura** [comment]
@ignasi35 I can verify that artifact can now be downloaded with the default resolvers:

```
$ sbt
[info] Loading global plugins from /Users/mj/.sbt/0.13/plugins
[info] Loading project definition from /Users/mj/workspace/lagom-pet-store/project
[info] Updating {file:/Users/mj/workspace/lagom-pet-store/project/}lagom-pet-store-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.lightbend.lagom/lagom-descriptor-generator-sbt-plugin/scala_2.10/sbt_0.13/0.0.2/jars/lagom-descriptor-generator-sbt-plugin.jar ...
[info] 	[SUCCESSFUL ] com.lightbend.lagom#lagom-descriptor-generator-sbt-plugin;0.0.2!lagom-descriptor-generator-sbt-plugin.jar (2422ms)
[info] Done updating.
[info] Set current project to pet-store (in build file:/Users/mj/workspace/lagom-pet-store/)
```
